export const WELLNESS_ENTRY_CREATE_REQUEST = 'WELLNESS_ENTRY_CREATE_REQUEST';
export const WELLNESS_ENTRY_CREATE_SUCCESS = 'WELLNESS_ENTRY_CREATE_SUCCESS';
export const WELLNESS_ENTRY_CREATE_FAIL = 'WELLNESS_ENTRY_CREATE_FAIL';
export const WELLNESS_ENTRY_CREATE_RESET = 'WELLNESS_ENTRY_CREATE_RESET';

export const WELLNESS_ENTRY_LIST_MY_REQUEST = 'WELLNESS_ENTRY_LIST_MY_REQUEST';
export const WELLNESS_ENTRY_LIST_MY_SUCCESS = 'WELLNESS_ENTRY_LIST_MY_SUCCESS';
export const WELLNESS_ENTRY_LIST_MY_FAIL = 'WELLNESS_ENTRY_LIST_MY_FAIL';
export const WELLNESS_ENTRY_LIST_MY_RESET = 'WELLNESS_ENTRY_LIST_MY_RESET';
